export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING"
export const RESET_PRODUCTS_LOADING = "RESET_PRODUCTS_LOADING"

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMUVE_FROM_WISHLIST = "REMUVE_FROM_WISHLIST"
export const ADD_TO_CART ="ADD_TO_CART"
export const REMUVE_FROM_CART ="REMUVE_FROM_CART"